from app.models.aeroclube import Aeroclube
from app.models.usuario import Usuario
from app.models.aeronave import Aeronave
from app.models.agendamento import Agendamento
from app.models.acionamento import Acionamento
from app.models.financeiro import Financeiro
from app.models.configuracao import Configuracao
from app.models.controlador import Controlador
from app.models.log import Log
from app.models.alerta import Alerta
